apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: chatapp-api
          image: ghcr.io/lucaschan1020/chatapp-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
            - name: GAPI_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: gapi-clientid-secret
                  key: GAPI_CLIENTID
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_DBURI
            - name: MONGODB_NAME
              value: ChatAppDev
